//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LID { get; set; }
        public string UIDorTELLNUMBER { get; set; }
        public int ActionType { get; set; }
        public int Result { get; set; }
        public System.DateTime Time { get; set; }
        public string Exception { get; set; }
    }
}
