//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        public int SID { get; set; }
        public int LevelNumber { get; set; }
        public int UnitNumber { get; set; }
        public int LessonNumber { get; set; }
        public int SlideNumber { get; set; }
        public string SlideName { get; set; }
        public string Context { get; set; }
    }
}
